FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    docker.io \
    curl \
    git \
    sshpass \
    systemd \
    && apt-get clean

RUN pip install --upgrade pip

RUN pip install \
    ansible \
    ansible-compat \
    molecule \
    molecule-docker \
    molecule-podman \
    cookiecutter

WORKDIR /opt/vector-role
