---
- name: Create extraction directory
  file:
    path: "/opt/vector"
    state: directory
    mode: "0755"

- name: Download and Extract Vector
  unarchive:
    src: "https://github.com/vectordotdev/vector/releases/download/v{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/opt/vector"
    remote_src: yes
    extra_opts: [--strip-components=2]

- name: Move Vector binary to bin
  copy:
    src: "/opt/vector/bin/vector"
    dest: "{{ vector_bin_path }}"
    mode: "0755"
    remote_src: true

- name: Create Vector config directory
  file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: "0755"

- name: Deploy Vector config
  template:
    src: vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"

- name: Create Vector systemd unit
  template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
  notify: Restart vector

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start Vector
  systemd:
    name: vector
    state: started
    enabled: true
