---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance-light
    image: docker.io/library/debian:11
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
