---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:latest
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: oraclelinux
    image: oraclelinux:8
    command: /usr/lib/systemd/systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK_DIR:-../../molecule/default}/converge.yml
    prepare: ${MOLECULE_PLAYBOOK_DIR:-../../molecule/default}/prepare.yml
    verify: ${MOLECULE_PLAYBOOK_DIR:-../../molecule/default}/verify.yml
verifier:
  name: ansible
